### PR TITLE
mDNS Support

### PR DESCRIPTION
**Pull request by kevinahuber**
This adds mDNS support using node-mDNS.

You can see the service published using bonjour on OSX:
`dns-sd -B`

I did not add any UI components- do you think a user should have a choice in broadcast method? Be able to do both at the same time?

### CODE REVIEW

**Comment by dermike** [comment]
Thanks! Will take a look and think about the UI!

**Comment by rochforp** [comment]
Nice! Thanks @kahjav and @dermike. I think a choice of which to broadcast on the UI maybe with a little tooltip since most users might just be looking for a quick and easy solution for eddy-url options

**Comment by dermike** [comment]
screen shot 2016-04-06 at 14 01 43

Working on this for UI, with matching application menu options.

**Comment by kevinahuber** [comment]
Nice! Are those on/off toggles?

**Comment by dermike** [comment]
@kahjav yes, exactly!

**Comment by dermike** [comment]
@kahjav UI added... can you please test? My PW iOS client crashed when advertising both mDNS and BLE at the same time.
I might know too little about mDNS, but shouldn't the whole url after the domain be txtRecord/path?

**Comment by dermike** [comment]
@kahjav https and full path fixed now :)

**Comment by rochforp** [comment]
@kahjav @dermike I just ran it and I'm seeing that mDNS isn't stopping when starting a new mDNS broadcast and I'm also seeing crashes in the iOS Physical Web app. If I get off of the wifi network the mDNS beacons are on, then of course, Phy Web app is working again. Just tested with two separate machines on the same wifi network and then you are able to see two mDNS beacons on the same network but only if they are coming from separate machines. Would a user want the ability to do both mDNS and bluetooth simultaniously with the same url or would the ability to split mDNS and bt urls on the UI be handy? I can help poke around the code after work : )
screenshot 2016-04-06 12 04 31
screenshot 2016-04-06 12 03 53

**Comment by dermike** [comment]
@rochforp cool! I just pushed a change that stops mdns before starting a new one. Any improvements are very appreciated! 

I also disabled mdns by default since right now you won't see an error if an url is too long for BLE. Maybe it should just be one protocol at a time? I'm pretty sure I got some urls to work in the iOS client when advertising with both methods.

**Comment by rochforp** [comment]
Just pulled the most recent version and everything is looking good now. No crashes and also running multiple mDNS beacons from my machine 👍 
screenshot 2016-04-06 13 31 26
img_1110

**Comment by rochforp** [comment]
Yikes! Sorry for the huge image

**Comment by dermike** [comment]
@rochforp I'm suspecting the crashes could have been caused by using port 80 for https which is fixed now

**Comment by rochforp** [comment]
@dermike ahh, good catch.

**Comment by kevinahuber** [comment]
Golden :) looks great! Thankya

**Pull request merged**
